system:
  debug:
    log_level: debug
ai:
  provider: "openai" # "openai" or "vertexai"
  openai:
    model: "gpt-3.5-turbo" # Check the list of available models by curl https://api.openai.com/v1/models -H "Authorization: Bearer $OPENAI_API_KEY"
  vertexai:
    project: "<YOUR_PROJECT_ID>"
    location: "us-central1"
    model: "gemini-1.5-flash-001"
  commands:
    - describe:
        description: "課題の詳細な説明を作成します。"
        system_prompt: "以下はGitHub Issueとそれに対するコメントです。詳細な説明を作成してください。\n"
    - suggest:
        description: "課題の内容に基づいて改善案を提示する。"
        system_prompt: "以下はGitHubのIssueとそれに対するコメントです。Issueの内容から解決すべき課題を特定し、改善案を3つ提示してください。\n"
    - ask:
        description: "フリーテキストの質問に答える。"
        system_prompt: "以下はGitHubのIssueとそれに対するコメントです。その内容に基づいて、以下の質問に対して詳細な回答をしてください\n"