name: Issue Comment Bot

on:
  issue_comment:
    types: [created]

jobs:
  bot-action:
    if: github.event.comment.user.login != 'ALERTBOT-chain' # ボットアカウント名を指定
    runs-on: ubuntu-latest
    steps:
      - name: Respond to Issue Comment
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.ALERTBOT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments \
            -d '{"body": "Thank you for your comment! This response is automated."}'
