name: "Comment run"
on:
  issue_comment:
    types: [created, edited]

jobs:
  comment-run:
    runs-on: ubuntu-22.04
    permissions:
      issues: write  # 必要な権限を明示
    steps:
    - uses: actions/checkout@v4
    - uses: nwtgck/actions-comment-run@v3
      with:
        github-token: ${{ secrets.ALER_MENTA_TOKEN }}  # 必要に応じてカスタムトークン
        allowed-associations: '["OWNER"]'

